kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

#workspace:
#  base: /go
# path: src/code.gitea.io/gitea
  
steps:
  - name: build
    pull: always
    image: golang:1.13
    commands:
      - go test

