kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: unit-test-1.13
    pull: always
    image: golang:1.13
    commands:
      - go test

  - name: unit-test-1.14
    pull: always
    image: golang:1.14
    commands:
      - go test

  - name: unit-test-1.15
    pull: always
    image: golang:1.15
    commands:
      - go test
