kind: pipeline
  build:
    image: debian:latest

name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.11
    commands:
      - go vet ./...
      - go test ./...
